#!/usr/bin/python

import cgi
import urllib
import urllib2
import cgitb

cgitb.enable()

urllib.urlcleanup()

url = "http://localhost"

params = cgi.FieldStorage()


if "url" in params:
  url = params["url"].value
  
#get the url
req = urllib2.Request(url)
req.add_header("user-agent","tinyproxy")
req.add_header("cache-control","no-cache")
req.add_header("pragma","no-cache")
resp = urllib2.urlopen(req)

headers = resp.info()
body = resp.read()


headers["transfer-encoding"] = ""

#headers
for key in headers.keys():
 print key+": "+headers[key]
print

#body
print body
 



