#!/usr/bin/python

import os
import cgi
import urllib2
from urllib2 import URLError,Request,urlopen
import cgitb

cgitb.enable()
url = "http://localhost"
params = cgi.FieldStorage()
#collect request headers
reqheaders = dict();
for param in os.environ.keys():
    if ( param.startswith("HTTP")):
      val = os.environ[param]
      key = param.replace("HTTP_","",1)
      key = key.replace("_","-")            
      reqheaders[key] = val     

if "url" in params:
  url = params["url"].value

#build request
req = Request(url)
req.add_header("user-agent","tRowser-Proxy")
req.add_header("cache-control","no-cache")
req.add_header("pragma","no-cache")

#original headers
for k, v in reqheaders.iteritems():
  req.add_header(k,v)

opener = urllib2.build_opener(urllib2.HTTPRedirectHandler)

resp = opener.open(req);
#try:
#    resp = opener.open(req)
#except URLError, e:        
#    resp = e

headers = resp.info()
body = resp.read()

headers["transfer-encoding"] = ""

#headers
for key in headers.keys():
 print key+": "+headers[key]
print

#body
print body 



